import "./globals.css";

// locale font import
import LocalFont from "next/font/local";

// remote font import
import { Oswald } from "next/font/google";
import Header from "@/components/header";

// remote font kurulum
const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald", // css değişken ismi
});

// local font kurulum
const skynight = LocalFont({
  src: "../assets/Skynight.otf",
  variable: "--font-skynight",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${skynight.variable} antialiased flex flex-col`}>
        <Header />

        <main className="flex-1 text-3xl p-10 text-center my-5">{children}</main>
      </body>
    </html>
  );
}
