import "./globals.css";

// locale font import
import LocalFont from "next/font/local";

// remote font import
import { Oswald } from "next/font/google";
import Link from "next/link";
import { fetchRecipes } from "@/utils/api";

// remote font kurulum
const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald", // css değişken ismi
});

// local font kurulum
const skynight = LocalFont({
  src: "../assets/Skynight.otf",
  variable: "--font-skynight",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await fetchRecipes();

  return (
    <html lang="en">
      <body className={`${oswald.variable} ${skynight.variable} antialiased flex flex-col`}>
        <header className="border-b p-4 space-x-10 flex justify-center">
          <Link href="/about">Hakkımızda (S)</Link>
          <Link href="/contact">İletişim (C)</Link>
          <Link href="/recipes-client">Tarifler (C)</Link>
          <Link href="/recipes-server">Tarifler - {data.recipes.length} (S)</Link>
        </header>

        <main className="flex-1 text-3xl p-10 text-center my-5">{children}</main>
      </body>
    </html>
  );
}
